[package]
name = "nekoton-core"
description = "TODO"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
everscale-crypto = { workspace = true }
everscale-types = { workspace = true }
serde = { workspace = true }

# local deps
nekoton-utils = { workspace = true }